---
- name: Get registration tokens
  uri: 
    method: GET 
    status_code: 200 
    url: "http://10.0.2.15:8080/v2-beta/projects/1a5/registrationtokens"
#    user: 450E14D8135D8C3348AE
#    password: xRffuGrNvQDo3kiEr4Zo1Lj2A6pcJPyAarqXyDLr
  register: registration_tokens
